### ISSUE TITLE
Danish lang

### ISSUE THREAD

**Issue by Alexey-T** [apertium/apertium-dan-nor#1]
Hi, can you pls, help with Danish lang for CudaText? information at http://wiki.freepascal.org/CudaText#How_to_make_translation

**Comment by TinoDidriksen** [comment]
Don't use issue trackers as contact forms or discussion boards, especially for tasks entirely unrelated to machine translation between Danish and Norwegian. Instead, see http://wiki.apertium.org/wiki/Contact
